version: '3.8'

networks:
  net:

services:
#nginx
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/nginx.dockerfile
    volumes:
      - ./web:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8000:80
    networks:
      - net
    depends_on:
      - php
#php
  php:
    build:
      context: .
      dockerfile: ./.docker/php/php.dockerfile
    volumes:
      - ./web:/var/www
    networks:
      - net
    depends_on:
      - mysql
#mysql
  mysql:
    image: mysql:5.7.24
    tty: true
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "7776:3306"
    command: [mysqld, --default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_DATABASE: project
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    networks:
      - net
#phpmyadmin     
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8001:80
    networks:
      - net
